---
title: "CCLE_GDSC_27_11_19"
author: "Kieran Redpath"
date: "27 November 2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Load Packages}
setwd("~/Documents/R Data/summer_project")
# Packages
library(limma)
library(edgeR)
library(data.table)
library(magrittr)
library(ggplot2)
library(CePa)
library(dplyr)
library(tidyverse)
library(ggbeeswarm)
```

```{r Load Documents}
CCLE_dasat_BCCCGC <- read.csv("CCLE_GDSC/Data/CCLE_dasat_BCCCGC.csv")
View(CCLE_dasat_BCCCGC)
CDH1_Exp_Levels <- read.csv("CCLE_GDSC/Data/CDH1_Exp_Levels.csv")
View(CDH1_Exp_Levels)
```

#27_11_19

```{r Create a Really Good Table, With All the Data in it}
# Remove the unneccesary "CDH1_Expression" column from "CCLE_dasat_BCCCGC"
CCLE_dasat_BCCCGC <- subset(CCLE_dasat_BCCCGC, select= -c(CDH1_Expression))
View(CCLE_dasat_BCCCGC)
# Merge "CCLE_dasat_BCCCGC" and "CDH1_Exp_Levels", to add expression data to "CCLE_dasat_BCCCGC"
CCLE_dasat_CDH1 = full_join(x=CCLE_dasat_BCCCGC, y=CDH1_Exp_Levels,  by=c("CCLE_Name" = "CCLE_Name"))
CCLE_dasat_CDH1 <- CCLE_dasat_CDH1 %>%
  filter(`Primary.Disease`=="Gastric Cancer"|`Primary.Disease`=="Breast Cancer" |`Primary.Disease`=="Colon Cancer")
View(CCLE_dasat_CDH1)
# Note that "CCLE_dasat_BCCCGC" has 202 entries, but we only have CDH1 expression data from ~108 of these (however, all drug treated samples are within this).
#Tidy up column names a bit
CCLE_dasat_CDH1 <- CCLE_dasat_CDH1 %>% 
  rename(
    Normalised_CDH1_Expression = ENSG00000039068.14,
    CDH1_Expression_Levels = CDH1_Expression,
    Sanger_ID = Sanger.ID,
    Primary_Disease = Primary.Disease,
    Subtype_Disease = Subtype.Disease
    )
View(CCLE_dasat_CDH1)
# Save the file as a .csv
write.csv(CCLE_dasat_CDH1,"~/Documents/R Data/summer_project/CCLE_GDSC/Data/CCLE_dasat_CDH1.csv", row.names = FALSE)
```


```{r Plot AUC/IC50 vs. CDH1 Expression Levels}
# Run this if  you don't already have "CCLE_dasat_CDH1" available:
# CCLE_dasat_CDH1 <- read.csv("~/Documents/R Data/summer_project/CCLE_GDSC/Data/CCLE_dasat_CDH1.csv")
# AUC ggplot (with CDH1 expression levels)
ggplot(data=CCLE_dasat_CDH1, mapping=aes(x=CDH1_Expression_Levels, y=AUC, fill=CDH1_Expression_Levels)) +
  labs(x= "Level of CDH1 Expression", y="AUC", caption="(Data from GDSC and CCLE)") +
  ggtitle("Dasatinib Data", subtitle="AUC vs Level of CDH1 Expression") +
  geom_boxplot() +
  geom_beeswarm()
# IC50 ggplot (with CDH1 expression levels)
ggplot(data=CCLE_dasat_CDH1, mapping =aes(x=CDH1_Expression_Levels, y=IC50, fill=CDH1_Expression_Levels)) +
  labs(x= "Level of CDH1 Expression",y="IC50", caption="(Data from GDSC and CCLE)") +
  ggtitle("Dasatinib Data", subtitle="IC50 vs Level of CDH1 Expresion") +
  geom_boxplot() +
  geom_beeswarm()
# Hmmm, doesn't look good.
```



```{r Plot Expression vs. Mutation Status, to Try Find out Where the Problem Lies}
ggplot(data=CCLE_dasat_CDH1, mapping=aes(x=CDH1_Mutations, y=Normalised_CDH1_Expression, fill=CDH1_Mutations)) +
  labs(x= "Number of CDH1 Mutations", y="Normalised CDH1 Expression", caption="(Data from GDSC and CCLE)") +
  ggtitle("CDH1 Data", subtitle="Normalised CDH1 Expression vs Number of CDH1 Mutations") +
  geom_boxplot() +
  geom_beeswarm()
#Hmmmmm... This still doesn't look good, does it?
```



Also do expression vs mutation status (I.e does expression level correlate with mutation)